name: localplayer
description: "LocalPlayer"
version: 1.0.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^15.1.2
  bloc: ^9.0.0
  iconify_flutter: ^0.0.7
  flutter_bloc: ^9.1.1
  flutter_card_swiper: ^7.0.2
  google_fonts: ^6.2.1
  webview_flutter: ^4.13.0
  just_audio: ^0.9.36
  just_audio_windows: ^0.2.1
  url_launcher: ^6.3.1
  http: ^1.4.0
  oauth2: ^2.0.3
  audioplayers: ^6.4.0
  latlong2: ^0.9.1
  colorful_iconify_flutter: ^0.0.5
  ini: ^2.1.0
  flutter_map: ^8.1.1
  dio: ^5.8.0+1
  equatable: ^2.0.7
  fluttertoast: ^8.2.12
  shared_preferences: ^2.5.3
  path_provider: ^2.1.2
  connectivity_plus: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  test: ^1.25.15

flutter:
  uses-material-design: true
  assets:
    - assets/profiles.json
    - assets/config.ini
    - assets/LocalPlayer.png